(function(g){var window=this;var d8=function(a,b){return g.aa[a]=b},dsa=function(a,b){var c=new g.pp;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},e8=function(a){return a.g?a.g.languageCode:a.o},f8=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.qp(a),kind:a.B,name:a.C,id:a.Ea,is_servable:a.O,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},g8=function(a,b,c,d,e){g.wm.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.Ij=[]},h8=function(a,b,c,d,e,f,k){g.wm.call(this,a,a+b,{priority:c,
namespace:"captions"});this.windowId=d;this.text=e;this.C=f||!1;this.o=k||null},esa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.mo=!0;break;case "u":k.Xo=!0;break;case "font":var m=f.getAttribute("color");i8.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new h8(a,b,c,d,n.nodeValue,e||0<m,g.Tb(k)?void 0:k));else{var q={};g.wa(q,k);esa(a,b,c,d,e||0<m,n,q,l)}}},j8=function(a){var b="_"+fsa++;
return new g8(0,0x8000000000000,0,b,a||{})},gsa=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Cv("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");esa(d,e,k,b,f,a.firstChild,{},c)},k8=function(){},hsa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},l8=function(){this.za=[]},m8=function(){this.g=null},isa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.mo=!0;break;case "u":l.Xo=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new h8(b,c,d,e.id,q.nodeValue,f||0<n,g.Tb(l)?void 0:l),m.push(q),e!=a.g&&e.Ij.push(q);else{var t={};g.wa(t,l);isa(a,b,c,d,e,!0,q,t,m)}}},n8=function(a){a=a.split(":");
for(var b=0,c=0;c<a.length;c++)b=60*b+(0,window.parseFloat)(a[c]);return 1E3*b},jsa=function(){this.A=[];
this.g=[];this.o=-1},o8=function(a,b){return b?a.g.concat(a.A):a.g},p8=function(a,b){switch(b.B){case "asr":ksa(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;ksa(b,a.g)}},ksa=function(a,b){g.Xa(b,(0,g.z)(a.J,a))||b.push(a)},lsa=function(a,b){var c=g.Wa(a.g,(0,g.z)(b.J,b));
-1!=c&&(a.o=c)},q8=function(a){this.g={};
this.B={};this.C={};this.A=a},r8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},s8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},t8=function(a,b){var c=r8(a,b);
if(void 0!=c)return c},u8=function(a,b){var c=a.getAttribute(b);
if(null!=c)return i8.test(c),c},msa=function(a,b){var c={},d=b.getAttribute("ws");
g.wa(c,d?a.C[d]:a.A);d=t8(b,"mh");null!=d&&(c.qo=d);d=t8(b,"ju");null!=d&&(c.textAlign=d);d=t8(b,"pd");null!=d&&(c.Ch=d);d=u8(b,"wfc");null!=d&&(c.windowColor=d);d=r8(b,"wfo");void 0!=d&&(c.Gh=d/255);return c},nsa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.wa(c,a.B[d]);d=t8(b,"ap");null!=d&&(c.cg=d);d=r8(b,"cc");null!=d&&(c.hs=d);d=r8(b,"ah");null!=d&&(c.mh=d);d=r8(b,"rc");null!=d&&(c.Ui=d);d=r8(b,"av");null!=d&&(c.Dh=d);return c},osa=function(a,b,c){var d={};
g.wa(d,nsa(a,b));g.wa(d,msa(a,b));c?(c="_"+fsa++,hsa(d,a.A)&&(d=a.A)):c=b.getAttribute("id")||"0";a=r8(b,"t");b=r8(b,"d")||0x8000000000000;return new g8(a,b,0,c,d)},v8=function(){this.A={};
this.g=null},w8=function(a){this.A=a;
this.g=null},x8=function(a){if(!psa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(qsa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},y8=function(a,b,c,d){g.H.call(this);
this.H=b;this.C=new l8;this.g=null;this.G=d;this.o=this.A=null;this.L=c;this.D=new g.Ld(this.F,1E3,this);g.J(this,this.D);b.addEventListener("seekto",this.B,this);this.B(b.getCurrentTime());this.F()},z8=function(a){this.eu=!!a;
this.g=new jsa;this.D=[];this.A=null},ssa=function(a){var b={};
if(a=e8(a))b.lang=a,rsa.test(a)&&(b.Ch=1);return b},tsa=function(a,b){return g.Xa(o8(a.g,!0),function(a){return a.toString()==b})},A8=function(a,b,c,d,e,f){this.C=[];
this.H=!1;this.A=a;this.F=[];this.G=[];this.wa=e;this.xa=f;this.D=null;this.V=.96*e;this.ka=.96*f;this.o={};g.wa(this.o,b);g.wa(this.o,this.A.params);g.wa(this.o,c);e={};g.wa(e,b.$a);this.A.params.$a&&g.wa(e,this.A.params.$a);g.wa(e,c.$a);this.o.$a=e;this.pa=c;g.V.call(this,{K:"div",Z:"caption-window",X:{id:"caption-window-"+a.id,dir:1==this.o.Ch?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:this.o.lang},T:[{K:"span",Z:"captions-text"}]});this.B=this.ua["captions-text"];this.ga=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=0;this.ba=this.J*usa(e);a=new g.Vy(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.oN,this);a.subscribe("dragmove",this.nN,this);a.subscribe("dragend",this.mN,this);this.da=this.ca=0;a="";this.o.Gh&&(a=x8(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Gh+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":vsa[this.o.textAlign]};this.ga&&(b["border-radius"]=a?this.ba/
8+"px":"");g.Vj(this.element,b);switch(this.o.cg){case 0:case 1:case 2:g.O(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.O(this.element,"ytp-caption-window-bottom")}},usa=function(a){var b=1+.25*(a.Sg||0);
if(0==a.offset||2==a.offset)b*=.8;return b},B8=function(a,b){var c={};
if(null!=b.Vd||b.background){var d=null!=b.Vd?b.Vd:a.o.$a.Vd,e=x8(b.background?b.background:a.o.$a.background);c.background="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ba/8+"px")}if(null!=b.Sg||null!=b.offset)c["font-size"]=a.J*usa(b)+"px";e=1;if(b.color||null!=b.Rf)d=x8(b.color||a.o.$a.color),e=null==b.Rf?a.o.$a.Rf:b.Rf,d="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")",c.color=d,c.fill=d;if(null!=b.ff&&0!=b.ff){var d="rgba(34, 34, 34, "+e+")",f=
"rgba(204, 204, 204, "+e+")";b.Ur&&(f=d=b.Ur);var k=a.J/16/2,l=Math.max(k,1),m=Math.max(2*k,1),e=Math.max(3*k,1),n=Math.max(5*k,1),q=[];switch(b.ff){case 4:for(l=e;l<=n;l+=k)q.push(m+"px "+m+"px "+l+"px "+d);break;case 1:for(k=2<=window.devicePixelRatio?.5:1;l<=e;l+=k)q.push(l+"px "+l+"px "+d);break;case 2:q.push(l+"px "+l+"px "+f);q.push(-l+"px "+-l+"px "+d);break;case 3:for(l=0;5>l;l++)q.push("0 0 "+m+"px "+d)}c["text-shadow"]=q.join(", ")}d="";switch(b.fontFamily){case 1:d='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:d='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:d='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:d='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:d='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:d=g.ti()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:d=
'Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}d&&(c["font-family"]=d);d=b.offset;null==d&&(d=a.o.$a.offset);switch(d){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.mo&&(c["font-style"]="italic");b.Xo&&(c["text-decoration"]="underline");b.Hn&&(c.visibility="hidden");return c},wsa=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];
g.y(d.text)&&(b+=d.text.split("\n").length-1,d.C||0==c||b++)}return b},xsa=function(a,b,c){a.H=a.H||!!c;
var d={};g.wa(d,a.o.$a);g.wa(d,c||b.o);g.wa(d,a.pa.$a);var e=a.F[0],f;if(e&&d.background==e.background&&d.Vd==e.Vd&&!!d.Hn==!!e.Hn&&d.ff==e.ff){for(c=0;c<a.F.length;c++)if(hsa(d,a.F[c])){f=a.G[c];break}if(!f){c={};for(var k in d)d[k]!=e[k]&&(c[k]=d[k]);f=g.Pe("SPAN");g.Vj(f,B8(a,c));a.G[0].appendChild(f);c=1}a.G.length=c;a.F.length=c}else a.G.length=0,a.F.length=0,f=g.Pe("SPAN"),g.Vj(f,B8(a,d)),a.B.appendChild(f);a.D&&a.D.parentNode!=f&&(g.We(a.D),f.appendChild(a.D));e=(k=g.y(b.text))?b.text.split("\n"):
[b.text];for(c=0;c<e.length;c++){var l=e[c];if(0<c||0==a.C.length||!b.C){if(0<c||0!=a.C.length){var m=g.Pe("BR");f.appendChild(m)}f.appendChild(g.Qe("\u00a0"));a.D=g.Qe("\u00a0");f.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.Qe(l):l,m))}a.F.push(d);a.G.push(f);a.C.push(b)},C8=function(a,b,c,d){z8.call(this,d);
c=c||g.Nh(a).hl||"";c=c.split("_").join("-");this.B=g.Ph(a,{hl:c});this.C=b;this.F={};this.o=null},D8=function(a,b,c,d,e,f){A8.call(this,a,b,c,d,e,f);
g.O(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.$=0;this.fa=window.NaN;this.P=null;this.N=new g.Ld(this.ra,433,this);g.J(this,this.N)},E8=function(a){if(!a.L){var b=g.Pe("SPAN");
g.Vj(b,B8(a,a.o.$a));a.B.appendChild(b);b.appendChild(g.Qe("M"));var c=b.offsetHeight,d=g.Pe("BR");b.appendChild(d);b.appendChild(g.Qe("M"));a.L=b.offsetHeight-c;a.B.removeChild(b)}return a.L},F8=function(a,b,c,d,e,f){A8.call(this,a,b,c,d,e,f);
this.type=1},G8=function(a,b){z8.call(this);
this.B=a;this.Y=b;this.o=null},H8=function(a){z8.call(this,a.gc);
this.o=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},ysa=function(a){for(var b in a)delete a[b]},L8=function(a){g.Vt.call(this,a);
g.Ty();this.W=g.U(a);this.A=a.getVideoData();this.ba=g.Rl(a);this.Y=a;var b=null,c=g.Yh("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zh(c));this.P=b;this.C={$a:{}};this.D={$a:{}};this.H=[];this.G={};this.O={};this.L=!1;this.fa="1"==this.A.C.cc_auto_caps||"1"==this.W.O.cc_auto_caps;c=b=this.B=this.o=this.F=this.J=this.$=null;I8(this)||(b=new g.Ld(this.Kw,0,this),g.J(this,b),c=new g.Ld(this.XJ,2E3,this),g.J(this,c));this.V=b;this.da=c;this.N=new g.rn(this);g.J(this,this.N);I8(this)||
this.N.U(a,"resize",this.Zo);this.N.U(a,"onPlaybackAudioChange",this.YF);this.N.U(a,"crn_captions",this.TM,this);this.N.U(a,"crx_captions",this.UM,this);J8(this,K8(this,"display-settings")||{});zsa(this)&&this.load()},I8=function(a){return"3"!=a.W.B?!1:!!a.Y.app.F.ul()},Asa=function(a){var b;
a.A.captionTracks.length&&(b=a.g.mj().Or);if(3==b||1==a.W.ra||1==a.A.pr||"alwayson"==a.A.Ge("yt:cc"))return!0;if(2==a.W.ra){var c=K8(a,"module-enabled");if(null!=c)return!!c}return 2==b||"on"==a.A.Ge("yt:cc")},zsa=function(a){return I8(a)?!a.A.o:a.A.captionTracks.length&&a.g.mj().ek?!0:Asa(a)},Bsa=function(a,b){var c=null;
if(a.o){c=a.o.Ts();!c&&b&&(c=o8(a.o.g,!0)[0]);if(!c&&(b||a.fa)){var d=a.o.g.A;d.length&&(c=tsa(a.o,d[0].toString()))}c||(c=a.o.ik())}return c},M8=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.L=c);a.B=b;a.load(d)},J8=function(a,b,c){var d=N8.$a;
a.C={};g.wa(a.C,N8);a.C.$a={};g.wa(a.C.$a,d);a.D={$a:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;i8.test(f);e.$a.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;i8.test(f);e.$a.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||N8.windowColor;i8.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.Vd);e.$a.Vd=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Sg);e.$a.Sg=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.Rf);e.$a.Rf=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=N8.Gh);e.Gh=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.ff);e.$a.ff=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.$a.fontFamily=f;a.loaded&&a.Zo();c&&O8(a,"display-settings",b)},Dsa=function(a,b){if(b&&!a.F){var c=j8({Ch:0,
lang:"en"});a.F=[c,new h8(c.start,c.end-c.start,0,c.id,g.N("YTP_SAMPLE_SUBTITLES"))];g.jm(a.g,a.F)}else!b&&a.F&&(Csa(a,a.F),a.F=null)},Csa=function(a,b){g.lm(a.g,b);
(0,g.F)(b,function(a){g.gb(this.H,a)},a);
a.V.je()},Esa=function(a,b){return a&&g.y(a)&&i8.test(a)?a:b},Fsa=function(a,b){return g.qa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Hsa=function(a,b){if(a&&g.y(a)){var c=Gsa.indexOf(a);
return-1!=c?c:b}return b},Jsa=function(a,b){if(a&&g.y(a)){var c=Isa.indexOf(a);
return-1!=c?c:b}return b},Ksa=function(a,b){return g.qa(a)&&!(0,window.isNaN)(a)?g.oe(a,-2,4):b},K8=function(a,b){if(!a.P)return null;
var c;try{c=a.P.get(b)}catch(d){a.P.remove(b)}return c},O8=function(a,b,c){if(a.P)try{a.P.set(b,c)}catch(d){}};
g.pp.prototype.J=d8(4,function(a){return a?this.toString()==a.toString():!1});
g.on.prototype.ul=d8(3,function(){return!!this.g.textTracks});
g.nZ.prototype.ul=d8(2,function(){return!1});
g.on.prototype.Lj=d8(1,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.nZ.prototype.Lj=d8(0,function(){});
var fsa=0;g.B(g8,g.wm);g.B(h8,g.wm);var i8=/^#(?:[0-9a-f]{3}){1,2}$/i,psa=/^#(?:[0-9a-f]{3}){1,2}$/i,qsa=/#(.)(.)(.)/,Lsa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/,Msa=/(?:\r\n|\r|\n){2,}/,Nsa=/^NOTE/,Osa=0,rsa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;l8.prototype.contains=function(a){a=g.ub(this.za,a);return 0<=a||0>a&&1==(-a-1)%2};
l8.prototype.length=function(){return this.za.length/2};
g.B(m8,k8);
m8.prototype.o=function(a,b){for(var c=[],d=a.split(Msa),e=1;e<d.length;e++){var f=d[e],k=b,l=c;if(""!=f&&!Nsa.test(f)){var m=g.r3.exec(f);if(m&&3<=m.length){var n=n8(m[1]),m=n8(m[2])-n,f=f.substring(g.r3.lastIndex);g.r3.lastIndex=0;var k=n+k,n=m,q=f,m={};this.g||(this.g=j8({qo:0}),l.push(this.g));var t=this.g,f=5;if(0>q.indexOf("<"))l.push(new h8(k,n,f,t.id,q,!1,g.Tb(m)?void 0:m));else{q=q.split(Lsa);1!=q.length&&(f=6,t="_"+Osa++,t=new g8(k,n,f,t,{}),l.push(t));for(var v=k,x=0;x<q.length;x++){var A=q[x];
if(0==x%2){var G=g.Cv("<html>"+A+"</html>"),I;G.getElementsByTagName("parsererror").length?(I=G.createElement("span"),I.appendChild(G.createTextNode(A))):I=G.firstChild;isa(this,v,n-(v-k),f,t,0<x,I,m,l)}else v=n8(A)}}}g.r3.lastIndex=0}}return c};
g.B(q8,k8);
q8.prototype.o=function(a){a.firstChild.getAttribute("format");var b,c;a=a.firstChild.childNodes;for(var d=0;d<a.length;d++){var e=a[d];switch(e.tagName){case "head":b=e;break;case "body":c=e}}if(b)for(b=b.childNodes,a=0;a<b.length;a++){var f=b[a];switch(f.tagName){case "pen":var e=f.getAttribute("id"),d=this.g,k=f,f={},l=k.getAttribute("p");l&&g.wa(f,this.g[l]);l=s8(k,"b");null!=l&&(f.bold=l);l=s8(k,"i");null!=l&&(f.mo=l);l=s8(k,"u");null!=l&&(f.Xo=l);l=t8(k,"et");null!=l&&(f.ff=l);l=t8(k,"of");
null!=l&&(f.offset=l);l=u8(k,"bc");null!=l&&(f.background=l);l=u8(k,"ec");null!=l&&(f.Ur=l);l=u8(k,"fc");null!=l&&(f.color=l);l=t8(k,"fs");void 0!=l&&0!=l&&(f.fontFamily=l);l=r8(k,"sz");void 0!=l&&(f.Sg=l/100-1);l=r8(k,"bo");void 0!=l&&(f.Vd=l/255);k=r8(k,"fo");void 0!=k&&(f.Rf=k/255);d[e]=f;break;case "ws":d=f.getAttribute("id");this.C[d]=msa(this,f);break;case "wp":d=f.getAttribute("id"),this.B[d]=nsa(this,f)}}b=[];if(c)for(a={},c=c.childNodes,d=void 0,e=0;e<c.length;e++)switch(f=c[e],f.tagName){case "w":k=
osa(this,f,!1);if(f=a[k.id])f.end=k.start;a[k.id]=k;b.push(k);break;case "p":var m=f,n=d,k=[],l=r8(m,"t")||0,q=r8(m,"d")||0,t=m.getAttribute("w")||"0",v=!!s8(m,"a");n&&"\n"==n.text&&!v&&(v=!0);for(var n=v?6:5,x=this.g[m.getAttribute("p")],m=m.childNodes,A=0;A<m.length;A++){var G=m[A];0<A&&(v=!0);if("s"==G.tagName)var I=G,G=l,K=q,Za=t,tb=v,ob=n,Hd=I.textContent?I.textContent:"",Sb=this.g[I.getAttribute("p")],I=r8(I,"t")||0,G=new h8(G+I,K-I,ob,Za,Hd,tb,Sb);else G=new h8(l,q,n,t,G.textContent||"",v,
x);k.push(G)}l=k;if(0<l.length)for(d=l[l.length-1],k=a[l[0].windowId],k||(k=osa(this,f,!0),b.push(k)),f=0;f<l.length;f++)q=l[f],l[f].windowId=k.id,k.Ij.push(q),b.push(q)}return b};
g.B(v8,k8);
v8.prototype.o=function(a){var b=[];this.g||(this.g=j8(),this.A[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=b,e=c.getAttribute("id");a:{var f=c,k=this.A[e];if(f.getAttribute("t")||f.getAttribute("start")){c=f.getAttribute("start")?1E3*(0,window.parseFloat)(f.getAttribute("start")):(0,window.parseInt)(f.getAttribute("t"),10);k&&(k.end>=c?k.end=c:k=null);switch(f.getAttribute("op")){case "kill":c=null;break a;case "define":k=null}k||
(k=j8());var l={};k&&(g.wa(l,k.params),k=k.params.$a)&&(l.$a={},g.wa(l.$a,k));f.getAttribute("rc")&&(l.Ui=(0,window.parseInt)(f.getAttribute("rc"),10));f.getAttribute("cc")&&(l.hs=(0,window.parseInt)(f.getAttribute("cc"),10));f.getAttribute("ap")&&(k=(0,window.parseInt)(f.getAttribute("ap"),10),l.cg=0>k||8<k?7:k);f.getAttribute("ah")&&(l.mh=(0,window.parseInt)(f.getAttribute("ah"),10));f.getAttribute("av")&&(l.Dh=(0,window.parseInt)(f.getAttribute("av"),10));f.getAttribute("vs")&&(l.isVisible=!!f.getAttribute("vs"));
f.getAttribute("ju")&&(l.textAlign=(0,window.parseInt)(f.getAttribute("ju"),10));f.getAttribute("pd")&&(l.Ch=1,0==(0,window.parseInt)(f.getAttribute("pd"),10)&&(l.Ch=0));f.getAttribute("bc")&&(l.$a||(l.$a={}),l.$a.backgroundColor=f.getAttribute("bc"));f.getAttribute("bo")&&(l.$a||(l.$a={}),l.$a.Vd=(0,window.parseInt)(f.getAttribute("bo"),10)/100);f.getAttribute("fc")&&(l.$a||(l.$a={}),l.$a.color=f.getAttribute("fc"));f.getAttribute("sd")&&(l.AK=(0,window.parseInt)(f.getAttribute("sd"),10));k=(0,window.parseInt)(f.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(f.getAttribute("dur"))||0x8000000000000;f=f.getAttribute("id")||"0";c=new g8(c,k,0,f,l)}else c=null}this.A[e]=c;d.push(c);break;case "text":for(d=b,e=[],gsa(a,this.g.id,e),c=0;c<e.length;c++)l=e[c],this.A[l.windowId]&&d.push(l)}a=a.nextSibling}return b};
g.B(w8,k8);w8.prototype.o=function(a){var b=[];this.g||(this.g=j8(this.A),b.push(this.g));a=a.firstChild.childNodes;for(var c=0,d=a.length;c<d;c++)gsa(a[c],this.g.id,b);return b};
var vsa=["left","right","center"],Psa={Hn:!0};g.B(y8,g.H);y8.prototype.R=function(){y8.M.R.call(this);this.H.removeEventListener("seekto",this.B,this);this.o&&this.o.abort()};
y8.prototype.B=function(a){this.g=g.Va(this.L.ri(a).g)};
y8.prototype.F=function(){this.isDisposed();var a;if(a=null!==this.g)a=this.g,a=a.g.Ep(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.H.getCurrentTime())){a=this.g;a=a.g.Tl(a);if(!this.C.contains(a.g[0].A)){var b=g.dn(g.Rn(a));this.o=g.Pi(b,{format:"RAW",fd:(0,g.z)(this.J,this),withCredentials:!0});this.A=a;var b=this.C,c=this.A.g[0].A,d=g.ub(b.za,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.za[d-1]&&d<b.za.length&&1==b.za[d]-c?(g.fb(b.za,d),g.fb(b.za,d-1)):0<d&&1==c-b.za[d-1]?b.za[d-1]=c:
d<b.za.length&&1==b.za[d]-c?b.za[d]=c:(g.pb(b.za,d,0,c),g.pb(b.za,d+1,0,c)))}this.g=g.Va(a.g)}this.D.start()};
y8.prototype.J=function(a){this.isDisposed();null==a.responseText||400<=a.status||null===this.G||this.G(a.responseText,1E3*this.A.g[0].startTime);this.o=this.A=null};
g.B(z8,g.H);z8.prototype.Ts=function(a){var b=this.g.o,c=o8(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
z8.prototype.ik=function(){return null};
z8.prototype.hd=function(){this.A=null};
z8.prototype.R=function(){z8.M.R.call(this);this.hd()};
g.B(A8,g.V);g.h=A8.prototype;g.h.oN=function(a,b){var c=g.kk(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.O(this.element,"ytp-dragging")};
g.h.nN=function(a,b){var c=g.nk(this.element),d=a-this.ca-.02*this.wa,e=b-this.da-.02*this.xa,f=(d+c.width/2)/this.V*3,f=Math.floor(g.oe(f,0,2)),k=(e+c.height/2)/this.ka*3,k=Math.floor(g.oe(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.V,d=100*g.oe(d,0,1),c=(e+k/2*c.height)/this.ka,c=100*g.oe(c,0,1);this.A.params.cg=l;this.A.params.Dh=c;this.A.params.mh=d;this.o.cg=l;this.o.Dh=c;this.o.mh=d;this.zh(this.C)};
g.h.mN=function(){g.sh(this.element,"ytp-dragging")};
g.h.Pb=function(){return this.type};
g.h.zh=function(a){var b=Math.min(this.Vs(),this.V),c=this.Us();g.Vj(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.Gm(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.o.mh+2,e=this.o.cg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Dh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.B.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Vj(this.element,a)};
g.h.Gm=function(a){for(var b=0;b<a.length&&a[b]==this.C[b];b++);if(this.H||this.C.length>b)b=0,this.H=!1,this.C=[],this.F=[],this.G=[],this.D=null,g.Te(this.B);for(;b<a.length;b++)xsa(this,a[b])};
g.h.Vs=function(){return 0};
g.h.Us=function(){return 0};
g.h.toString=function(){return A8.M.toString.call(this)};
g.B(C8,z8);g.h=C8.prototype;g.h.no=function(a,b){this.isDisposed();var c=this.si(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.hd();this.o=g.Pi(c,{format:"RAW",Cb:d,withCredentials:!0});lsa(this.g,a)};
g.h.oo=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.eu&&(b.asrs=1);d=g.Ph(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=b.getElementsByTagName("track"),l=e.length,m=0;m<l;m++){var n=e[m].getAttribute("formats"),q=c,t=e[m].getAttribute("lang_code"),v=e[m].getAttribute("lang_translated"),x=e[m].getAttribute("name"),A=e[m].getAttribute("kind"),G=e[m].getAttribute("id"),I="true"==e[m].getAttribute("lang_default"),
K="true"==e[m].getAttribute("cantran"),Za=e[m].getAttribute("vss_id");p8(d,new g.pp({formats:n,format:q,languageCode:t,languageName:v,name:x,kind:A,id:G,is_servable:!0,is_default:I,is_translateable:K,vss_id:Za}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),m=b[e].getAttribute("lang_translated"),n=b[e].getAttribute("lang_original"),q=b[e].getAttribute("id"),t="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,
id:q,is_default:t},this.F[l.languageCode]=l.languageName,this.D.push(new g.op(l))}a()},this);
this.hd();this.o=g.Pi(d,{format:"RAW",Cb:b,withCredentials:!0})};
g.h.si=function(a){var b=this.B,c={v:this.C,type:"track",lang:a.o,name:a.getName(),kind:a.B,fmt:a.A};a.g&&(c.tlang=e8(a));return b=g.Ph(b,c)};
g.h.hd=function(){C8.M.hd.call(this);this.o&&this.o.abort()};
g.h.R=function(){this.hd();C8.M.R.call(this)};
g.B(D8,A8);D8.prototype.ra=function(){g.sh(this.element,"ytp-rollup-mode");var a=this.P;this.P=null;this.zh(a)};
D8.prototype.Vs=function(){var a=this.A.params.hs;if(!this.$&&a){var b=g.Pe("SPAN");g.ef(b,"\u00a0"+(0,g.Ja)("\u2014",a)+"\u00a0");g.Vj(b,B8(this,this.o.$a));this.B.appendChild(b);this.$=b.offsetWidth;this.B.removeChild(b)}return this.$};
D8.prototype.Us=function(){return this.A.params.Ui*E8(this)};
D8.prototype.zh=function(a){if(E8(this)){for(var b=0,c=0;b<this.C.length&&c<a.length;b++)this.C[b]==a[c]&&c++;var d=wsa(a),e=!1,b=0;if(0<c&&c<a.length){var c=this.C.concat(a.slice(c)),f=wsa(c)-d;0<f&&(this.P=a,a=c,b-=f,e=!0)}d<this.A.params.Ui&&(b+=this.A.params.Ui-d);e&&!this.N.isActive()&&(g.O(this.element,"ytp-rollup-mode"),this.N.start());b!=this.fa&&(d="",b&&(d="translateY("+Math.ceil(b*E8(this))+"px)"),g.Vj(this.B,"transform",d),this.fa=b);D8.M.zh.call(this,a)}else D8.M.zh.call(this,a)};
g.B(F8,A8);F8.prototype.Gm=function(a){var b=this.A.Ij;F8.M.Gm.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.wa(f,e.o),g.wa(f,Psa),c=e.o,d=f);xsa(this,e,f)}};
g.B(G8,z8);g.h=G8.prototype;g.h.no=function(a,b){this.hd();var c=this.B.g[a.o];c&&(this.o=new y8(0,this.Y,c,function(c,e){b(c,a,e)}))};
g.h.oo=function(a){p8(this.g,new g.pp({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.hd=function(){G8.M.hd.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.si=function(){return""};
g.h.R=function(){this.hd();G8.M.R.call(this)};
g.B(H8,z8);g.h=H8.prototype;g.h.no=function(a,b){this.isDisposed();var c=this.si(a),d=(0,g.z)(function(c){this.B=null;b(c.responseText,a)},this);
this.hd();this.B=g.Pi(c,{format:"RAW",Cb:d,withCredentials:!0});this.o&&this.o.ek!=a&&(this.o.Ym=a)};
g.h.oo=function(a,b,c,d){this.C=c;if(this.o=d||null)for(b=0;b<this.o.captionTracks.length;b++)p8(this.g,this.o.captionTracks[b]);a()};
g.h.si=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.Ph(b,c)};
g.h.ik=function(){return this.o?this.o.ek:null};
g.h.Ts=function(){return this.o?this.o.Ym:null};
g.h.hd=function(){H8.M.hd.call(this);this.B&&this.B.abort()};
g.h.R=function(){this.hd();H8.M.R.call(this)};
var N8={windowColor:"#080808",Gh:0,textAlign:2,cg:7,mh:50,Dh:100,$a:{background:"#080808",Vd:.75,ff:0,color:"#fff",fontFamily:4,Sg:0,Rf:1,offset:1}},Gsa=["none","raised","depressed","uniform","dropShadow"],Isa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" ");g.B(L8,g.Vt);g.h=L8.prototype;g.h.R=function(){I8(this)||Dsa(this,!1);L8.M.R.call(this)};
g.h.load=function(a){L8.M.load.call(this);if(this.o||a)this.B?(a?this.Cv(a,this.B):3!=this.g.ab()&&this.o.no(this.B,(0,g.z)(this.Cv,this)),this.g.ya("captionschanged",f8(this.B))):this.g.ya("onCaptionsTrackListChanged");else{var b;this.A.o?b=new G8(this.A.g,this.g):this.A.captionTracks.length?b=new H8(this.A):b=new C8(this.A.hc,this.A.videoId,this.A.nr||this.W.xc||this.A.Ge("yt:cc_default_lang")||this.W.Va,this.A.gc);this.o=b;b.oo((0,g.z)(this.YI,this),!0,I8(this)?"vtt":void 0,this.g.mj())}};
g.h.unload=function(){if(I8(this))for(var a=g.De("track",void 0,this.ba.o),b=0;b<a.length;b++)g.We(a[b]);else g.Nd(this.da),g.mm(this.g,"captions"),this.H=[],this.o&&this.o.hd(),this.F&&g.jm(this.g,this.F),this.Zo();L8.M.unload.call(this);(a=g.Pl(this.g.app))&&g.TU(a);this.g.ya("captionschanged",{})};
g.h.YI=function(){var a;if(this.L||Asa(this))a=Bsa(this,this.L);if(I8(this))for(var b=o8(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.qp(d),srclang:e8(d),src:this.o.si(d)};d==a&&(e["default"]=1);this.Y.app.F.Lj([g.M("TRACK",e)])}else!this.B&&a&&M8(this,a),this.g.ya("onCaptionsTrackListChanged"),this.g.ya("onApiChange")};
g.h.EK=function(){this.loaded&&!I8(this)&&this.unload()};
g.h.Cv=function(a,b,c){if(a){var d;d=this.o;c=c||0;"WEBVTT"==a.substring(0,6)?(d.A||(d.A=new m8),d=d.A.o(a,c)):(a=g.Cv(a))&&a.firstChild?(d.A||("timedtext"==a.firstChild.tagName?3==(0,window.parseInt)(a.firstChild.getAttribute("format"),10)?d.A=new q8(ssa(b)):d.A=new v8:d.A=new w8(ssa(b))),d=d.A.o(a,c)):d=[];a={trackName:b.getName(),trackKind:b.B,trackLangCode:e8(b)};b.g&&(a.fromLangCode=b.o);g.am(this.g,"cc",a);if(this.B!=this.o.ik()){if(this.L&&!g.Dn(this.W)&&!g.Bs(this.W)){g.Nd(this.da);b=j8({cg:0,
mh:5,Dh:5,Ui:2,textAlign:0,Ch:0,lang:"en"});this.J=[b];a=g.N("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.$||(c=new g.Xt(g.Sg()),g.J(this,c),this.$=c.element);c=b.end-b.start;var e=g.qp(this.B);e&&this.J.push(new h8(b.start,c,0,b.id,e));this.J.push(new h8(b.start,c,0,b.id,a[0]),new h8(b.start,c,0,b.id,this.$,!0),new h8(b.start,c,0,b.id,a[1],!0));g.jm(this.g,this.J);this.da.je()}(this.L||g.Dn(this.W))&&O8(this,"module-enabled",!0);(b=g.Pl(this.g.app))&&g.TU(b)}g.jm(this.g,d);this.L=!1}};
g.h.TM=function(a){this.H.push(a);this.V.je()};
g.h.UM=function(a){g.gb(this.H,a);this.V.je()};
g.h.OJ=function(a){if(a instanceof g8){var b=this.G[a.id];b&&b.A!=a&&(b.dispose(),delete this.G[a.id],b=null);if(!b){var b=this.G,c=a.id;a:{var d=this.ba.Ua(),e=g.SY(this.ba,!0).height;switch(null!=a.params.qo?a.params.qo:a.params.AK?2:1<a.Ij.length?1:0){case 1:a=new F8(a,this.C,this.D,e,d.width,d.height);break a;case 2:a=new D8(a,this.C,this.D,e,d.width,d.height);break a;default:a=new A8(a,this.C,this.D,e,d.width,d.height)}}b[c]=a}}else b=a.windowId,this.O[b]||(this.O[b]=[]),this.O[b].push(a)};
g.h.XJ=function(){Csa(this,this.J);this.J=null};
g.h.Kw=function(){this.V.stop();ysa(this.O);this.H.sort(g.xm);(0,g.F)(this.H,this.OJ,this);g.Gb(this.G,function(a,b){!this.O[b]||this.F&&-1==this.F.indexOf(a.A)?(a.dispose(),delete this.G[b]):(a.element.parentNode||g.pm(this.g,a.element,5),a.zh(this.O[b]))},this)};
g.h.Vv=function(){J8(this,{},!0)};
g.h.tn=function(){var a=N8.$a,a={background:a.background,backgroundOpacity:a.Vd,charEdgeStyle:a.ff,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Sg,textOpacity:a.Rf,windowColor:N8.windowColor,windowOpacity:N8.Gh},b=K8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.cp=function(a,b){var c={};g.wa(c,K8(this,"display-settings"));g.wa(c,a);J8(this,c,b);this.g.Ra("captionssettingschanged")};
g.h.Zo=function(){!I8(this)&&this.loaded&&(g.Gb(this.G,function(a,b){a.dispose();delete this.G[b]},this),this.Kw())};
g.h.Xx=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.oe(b,-2,4);this.cp({fontSizeIncrement:c});return c;case "reload":b&&!I8(this)&&M8(this,this.B,!0);break;case "stickyLoading":void 0!=b&&this.W.ob&&O8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(I8(this))break;if(!g.sa(b))break;if(g.Tb(b)){M8(this,null,!0);break}for(var d,e=o8(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
dsa(f,b.translationLanguage):f)}!d||d==this.B&&this.loaded||M8(this,d,!0)}else return this.loaded&&this.B&&this.B!=this.o.ik()?f8(this.B):{};return"";case "tracklist":return this.o?(0,g.Q)(o8(this.o.g,b&&b.includeAsr),function(a){return f8(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.tn();if(g.Dn(this.W)&&b&&g.sa(b))if(b.reset)this.Vv();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Esa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=Fsa(b[c],d[c]);break;case "charEdgeStyle":f[c]=Hsa(b[c],d[c]);break;case "fontSizeIncrement":f[c]=Ksa(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=Jsa(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.cp(f,!0);d=this.tn()}d.fontFamilyOption=Isa[d.fontFamily];d.charEdgeStyle=Gsa[d.charEdgeStyle];return d;case "sampleSubtitles":I8(this)||void 0==b||Dsa(this,!!b);break;case "xmlTrack":b&&this.W.ob&&!I8(this)&&M8(this,new g.pp({languageName:b.name}),!1,b.xml)}};
g.h.RM=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.W.ob&&a.push("stickyLoading","xmlTrack");return a};
g.h.SM=function(){var a=this.B;return a?{cc:a.F}:{}};
g.h.Hw=function(){this.loaded&&this.B?(O8(this,"module-enabled",!1),this.unload()):M8(this,this.B||Bsa(this,!0),!0)};
g.h.YF=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),zsa(this)&&this.load())};
window._exportCheck==g.ya&&g.ka("ytmod.player.captions",L8,void 0);})(_yt_player);
